<a href="https://colab.research.google.com/github/vasudev006/S2Codebase/blob/main/S2_EXPERIMENT_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Experiment No.2

#Aim
To study and implement basic numerical computation , symbolic mathematics and graphical visualisation using `python` libraries such as NumPy , SymPy and Matplotlib.


#Basic usage of `NumPy`

Numpy (Numerical Python) is the foundational library for scientific computing in python , It provides support for large ,multi-dimensional arrays and matrices,along with a collection of mathematical functions to operate on these arrays effectively.In this section,basic mathematical operations are tranlsated to python .For this simulation examples NumPy library will be used

In [ ]:
import numpy as np

#Mathematical Functions

NumPy allows us to perform elemnt-wise mathematical operations on arrays without using loops>**Simulating a basic mathematics functions**, y=f(x) **in data driven approach**

In [ ]:
#Sine function
angles=np.array([0,np.pi/2,np.pi])
sin_values=np.sin(angles)
print("Sine values:",sin_values)

#Exponential Finction
a=np.array([1,2,3])
exp_values=np.exp(a)
print("Exponential values:",exp_values)

#Square root function
sqrt_values=np.sqrt(a)
print("Square root values:",sqrt_values)

Sine values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponential values: [ 2.71828183  7.3890561  20.08553692]
Square root values: [1.         1.41421356 1.73205081]


##Array manipulation
understanding how to structure data is crucial.We can reshape arrays to change their dimensions or access specific elements using indexing and slicing

In [ ]:
#Reshaping a 1d rray to 2d
reshaped_array=np.arange(12).reshape(3,4)
print("Reshaped array:\n",reshaped_array)

#Indexing and slicing
array=np.array([1,2,3,4,5])

#Accessing an elemnt
print("Elemnt at index 2:",array[2])

#Skixcing (elemnts from index 1 up to ,but not including,4)
print("Elemnts from index 1 to 3:",array[1:4])

#Fancy indexing (aceessing specific non-consecutive indices)
indices=[0,2,4]
print("Elemnts at indices 0,2,4:",array[indices])

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Elemnt at index 2: 3
Elemnts from index 1 to 3: [2 3 4]
Elemnts at indices 0,2,4: [1 3 5]


#Aggregation Functions

In [ ]:
#Sum of elemnts
sum_value=np.sum(array)
print("Sum of elemnts:",sum_value)

#Mean of elemnts
mean_value=np.mean(array)
print("Mean of elemnts:",mean_value)

#Maximum and minimum values
print("Maximum value:",np.max(array))
print("Minimum value:",np.min(array))

Sum of elemnts: 15
Mean of elemnts: 3.0
Maximum value: 5
Minimum value: 1


##Broadcasting

In [ ]:
#Broadcasting a scalar value
scalar=5
broadcasted_sum=array+scalar
print("Array + scalar :\n",broadcasted_sum)

#Broadcasting with different  shapes
array_2d=np.array