<a href="https://colab.research.google.com/github/vasudev006/S2Codebase/blob/main/S2_EXPERIMENT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Experiment No.1

***Introducing python as a tool for computational mathematics***
✈

#Aim

To introduce python programming fundamentals and demonstarte its use as a computational tool for basic mathematical operation relevant to engineering mathematics

****




1.**Hello World**

The classic code for python command


In [ ]:
print("hello , world!")

hello , world!


2.**Basic Arithmetic operations**

Simple operations like addition subtraction multiplication and division

In [ ]:
#Addition
a=5;b=3
print("a+b=",a+b)

#Subtdaction
print("a-b=",a-b)

#Multiplication
print("Multiplication:",a*b)

#Division
print("Diviision:",a/b)

a+b= 8
a-b= 2
Multiplication: 15
Diviision: 1.6666666666666667


3.**Variable and data Types**

Introduction to different data types like integrs float,strings and complex

In [ ]:
#Integer
x=10
print("Data type of x is ",type(x))

#Float
y=3.14
print("Data type of y is ",type(y))

#String
z="Python"
print("Data type of z is ",type(z))

#Complex
c=2+3j
print("Data type of c is ",type(c))

Data type of x is  <class 'int'>
Data type of y is  <class 'float'>
Data type of z is  <class 'str'>
Data type of c is  <class 'complex'>


4.**Lists**

Creating and manipluating lists

In [ ]:
#Creating a List
fruits = ["apple", "banana", "cherry"]
print("list:",fruits)
#Acessing elemnts
print("fruits[0]:",fruits[0])
#adding an element
fruits.append("orange")
print("Updated list:",fruits)
#removing an elemnt
fruits.remove("banana")
print("list after removal",fruits)
#insert an element
fruits.insert(0,"banana")
print("new puthiya list",fruits)

list: ['apple', 'banana', 'cherry']
fruits[0]: apple
Updated list: ['apple', 'banana', 'cherry', 'orange']
list after removal ['apple', 'cherry', 'orange']
new puthiya list ['banana', 'apple', 'cherry', 'orange']


5.**Loops**

using for and while loops


In [ ]:
#For Loop
for i in range(5):
  print("for loop iteration",i)


for loop iteration 0
for loop iteration 1
for loop iteration 2
for loop iteration 3
for loop iteration 4


In [ ]:
#While Loop
count=0
while count <=5:
  print("while loop itertaion:",count)
  count+=1

while loop itertaion: 0
while loop itertaion: 1
while loop itertaion: 2
while loop itertaion: 3
while loop itertaion: 4
while loop itertaion: 5


6.**Conditional Statements**

Using if,elif and else statements.

In [ ]:
number=0
if number>0:
  print("positive number")
elif number==0:
  print("zero")
else:
  print("negative number")

zero


7.**Functions**

Defining and calling functions

In [5]:
#Definiong a function
def greet(name):
  return("hello, "+name)

#Calling a function
print(greet("Alice"))
print(greet("Kalyani"))

hello, Alice
hello, Klayani


#Basic usage of NumPy

**Importing NumPy**

In [ ]:
import numpy as np

8.**Creating arrays using numpy88**


In [ ]:
#Creating a 1d array
array_1d = np.array([1,2,3,4,5])
print("1d array:",array_1d)

#Creating a 2d array
array_2d = np.array([[1,2,3],[4,5,6]])
print("2d array:",array_2d)

1d array: [1 2 3 4 5]
2d array: [[1 2 3]
 [4 5 6]]


9.**Creating special array using NumPy**

In [ ]:
#Creating an array of zeros
zeros=np.zeros((2,3))
print("zeros array:\n",zeros)

#creating an array of ones
ones=np.ones((2,3))
print("array of ones:\n",ones)

#creating an array with a range of values
range_array=np.arange(10)
print("range array:\n",range_array)

#creating an array with evenly spaced values
linspace_array=np.linspace(0,1,5)
print("linspace array:",linspace_array)

zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
range array:
 [0 1 2 3 4 5 6 7 8 9]
linspace array: [0.   0.25 0.5  0.75 1.  ]


10.**Basic arithmetic operations**

In [2]:
import numpy as np

#elemnt based addition
a=np.array([1,2,3])
b=np.array([4,5,6])
print("addition:",a+b)

#elemnt wise subtracttion
print("subtraction:",a-b)

#element wise multiplication
print("multiplication:",a*b)

#element wise division
print("division:",a/b)

addition: [5 7 9]
subtraction: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]
