<a href="https://colab.research.google.com/github/vasudev006/S2Codebase/blob/main/S2_EXPERIMENT_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Experiment No.2

#Aim
To study and implement basic numerical computation , symbolic mathematics and graphical visualisation using `python` libraries such as NumPy , SymPy and Matplotlib.


#Basic usage of `NumPy`

Numpy (Numerical Python) is the foundational library for scientific computing in python , It provides support for large ,multi-dimensional arrays and matrices,along with a collection of mathematical functions to operate on these arrays effectively.In this section,basic mathematical operations are tranlsated to python .For this simulation examples NumPy library will be used

In [1]:
import numpy as np

#Mathematical Functions

NumPy allows us to perform elemnt-wise mathematical operations on arrays without using loops>**Simulating a basic mathematics functions**, y=f(x) **in data driven approach**

In [2]:
#Sine function
angles=np.array([0,np.pi/2,np.pi])
sin_values=np.sin(angles)
print("Sine values:",sin_values)

#Exponential Finction
a=np.array([1,2,3])
exp_values=np.exp(a)
print("Exponential values:",exp_values)

#Square root function
sqrt_values=np.sqrt(a)
print("Square root values:",sqrt_values)

Sine values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponential values: [ 2.71828183  7.3890561  20.08553692]
Square root values: [1.         1.41421356 1.73205081]


##Array manipulation
understanding how to structure data is crucial.We can reshape arrays to change their dimensions or access specific elements using indexing and slicing

In [3]:
#Reshaping a 1d rray to 2d
reshaped_array=np.arange(12).reshape(3,4)
print("Reshaped array:\n",reshaped_array)

#Indexing and slicing
array=np.array([1,2,3,4,5])

#Accessing an elemnt
print("Elemnt at index 2:",array[2])

#Skixcing (elemnts from index 1 up to ,but not including,4)
print("Elemnts from index 1 to 3:",array[1:4])

#Fancy indexing (aceessing specific non-consecutive indices)
indices=[0,2,4]
print("Elemnts at indices 0,2,4:",array[indices])

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Elemnt at index 2: 3
Elemnts from index 1 to 3: [2 3 4]
Elemnts at indices 0,2,4: [1 3 5]


#Aggregation Functions

In [4]:
#Sum of elemnts
sum_value=np.sum(array)
print("Sum of elemnts:",sum_value)

#Mean of elemnts
mean_value=np.mean(array)
print("Mean of elemnts:",mean_value)

#Maximum and minimum values
print("Maximum value:",np.max(array))
print("Minimum value:",np.min(array))

Sum of elemnts: 15
Mean of elemnts: 3.0
Maximum value: 5
Minimum value: 1


##Broadcasting

In [7]:
#Broadcasting a scalar value
scalar=5
broadcasted_sum=array+scalar
print("Array + scalar :\n",broadcasted_sum)

#Broadcasting with different  shapes
array_2d=np.array([[1,2,3],[4,5,6]])
array_1d=np.array([1,2,3])
broadcasted_sum_2d=array_2d + array_1d
print("2D array + 1d array:\n",broadcasted_sum_2d)

Array + scalar :
 [ 6  7  8  9 10]
2D array + 1d array:
 [[2 4 6]
 [5 7 9]]


#Symbolic Mathematics with SymPy

Basic Symbolic Computation

In [10]:
import sympy as sp

#Define symbols
x,y=sp.symbols('x y')

#Define an expression
expr=x**2+2*x+1

#Simplify the expression
simplified_expr=sp.simplify(expr)
print(f"Simplified expression: {simplified_expr}")

#Expand the expression
expanded_expr=sp.expand((x+1)**2)
print(f"Expanded expession:{expanded_expr}")

Simplified expression: x**2 + 2*x + 1
Expanded expession:x**2 + 2*x + 1


#Solving Equations

In [16]:
#Define equation:x^2-4=0
eq=sp.Eq(x**2-4,0)

#Solve for x
solutions=sp.solve(eq,x)
print(f"Solutions: {solutions}")

Solutions: [-2, 2]


#Calculus

In [17]:
#Define a function
f=sp.sin(x)*sp.exp(x)

#differentiate the function
f_prime=sp.diff(f,x)
print(f"Derivative: {f_prime}")

#Integrate the function
integral=sp.integrate(f,x)
print(f"Integral: {integral}")

Derivative: exp(x)*sin(x) + exp(x)*cos(x)
Integral: exp(x)*sin(x)/2 - exp(x)*cos(x)/2


#Limits and Series Expansion

In [18]:
#Limit of sin(x)/x as x approaches 0
f_limit=sp.sin(x)/x
limit_val=sp.limit(f_limit,x,0)
print(f"Limit: {limit_val}")

#Series expansion of e^x around x=0
f_exp=sp.exp(x)
series_f=sp.series(f_exp,x,0,6)
print(f"Series expansion: {series_f}")

Limit: 1
Series expansion: 1 + x + x**2/2 + x**3/6 + x**4/24 + x**5/120 + O(x**6)
